#
# \brief Default Travis for project
# \author Uilian Ries <uilianries@gmail.com>
#
sudo: required

dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake 

branches:
  only:
    - develop
