#
# \brief Default Travis for project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake doxygen cppcheck clang-3.6 graphviz
  - curl -s https://packagecloud.io/install/repositories/uilianries/poco/script.deb.sh | sudo bash && sudo apt-get install libpoco-1.7=1.7-1
  - git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cd build && cmake .. && make && sudo make install
  - cd ../.. && rm -rf googletest
  - git clone https://github.com/uilianries/MQTTClient.git && cd MQTTClient && mkdir build && cd build && cmake .. && make && sudo make install
  - cd ../.. && rm -rf MQTTClient

script:
  - script/doxygen.sh
  - script/cppcheck.sh
  - script/tidy.sh
  - mkdir build && cd build && cmake .. && make
  - sudo make install
  - test/application/test_application

branches:
  only:
    - develop
    - master
