#
# \brief Default Travis for project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake libcppunit-dev doxygen cppcheck clang-3.6
  - curl -s https://packagecloud.io/install/repositories/uilianries/poco/script.deb.sh | sudo bash && sudo apt-get install libpoco-1.7=1.7-1

script:
  - mkdir build && cd build && cmake .. && make
  - sudo make install
  - script/doxygen.sh
  - script/cppcheck.sh
  - script/tidy.sh
  - test/application/test

branches:
  only:
    - develop
