#
# \brief Default Travis for project
# \author Uilian Ries <uilianries@gmail.com>
#
dist: trusty

language: cpp

compiler: gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake libboost1.55-all-dev

script:
  - mkdir build && cd build && cmake .. && make

branches:
  only:
    - develop
